// Atlas Copco Market Intelligence — Data Layer
// Design: Nordic Industrial Precision

export interface Project {
  id: string;
  name: string;
  location: string;
  value: string;
  owner: string;
  priority: "hot" | "warm" | "cold";
  capexGrade: "A" | "B" | "Unknown";
  opportunityRoute: "Direct CAPEX" | "Fleet CAPEX" | "OPEX/Monitor";
  sector: "mining" | "oil_gas" | "infrastructure" | "energy" | "defence";
  isNew: boolean;
  stage: string;
  overview: string;
  equipmentSignals: string[];
  contractors: { name: string; status: "confirmed" | "predicted" | "unknown"; confidence?: number; detail?: string }[];
  opportunityNote?: string;
  sources: { label: string; url: string; date?: string }[];
  timeline?: string;
  completion?: string;
}

export interface Contact {
  name: string;
  title: string;
  company: string;
  project: string;
  priority: "hot" | "warm" | "cold";
  roleBucket: string;
  email?: string;
  linkedin?: string;
  phone?: string;
}

export interface DrillingCampaign {
  campaign: string;
  operator: string;
  location: string;
  drillType: string;
  timing: string;
  airRequirement: string;
  source: { label: string; url: string };
}

export interface AwardedProject {
  project: string;
  value: string;
  winningContractor: string;
  location: string;
  stage: string;
  opportunity: "Direct" | "Fleet" | "Monitor";
  source: { label: string; url: string };
}

export interface ResearchPass {
  pass: string;
  focus: string;
  rawProjects: number;
  keySources: string;
}

export const metadata = {
  generated: "2026-02-10T07:00:00+08:00",
  weekEnding: "Feb 10, 2026",
  generatedTime: "7:00 AM AWST",
};

export const stats = {
  totalProjects: 28,
  hotProjects: 5,
  warmProjects: 11,
  coldProjects: 12,
  confirmedContractors: 12,
  predictedContractors: 18,
  capexOpportunities: 15,
  totalContacts: 35,
  sourcesSearched: "20+",
};

export const executiveSummary = {
  mainText: `This week's intelligence sweep identified 28 deduplicated projects from 55 raw signals across 8 research passes and 20+ industry sources. The pipeline shows strong activity in Western Australia's Pilbara region and Queensland's Bowen Basin, with several high-value contract awards creating immediate opportunities for portable air equipment.`,
  actionItems: [
    "NRW Civil & Mining has $270M+ in new civil contracts requiring bulk earthworks — contact procurement immediately.",
    "Monadelphous secured $300M Rio Tinto maintenance — shutdown air needs imminent.",
    "Golding Meandu $750M MSA is in 6-month mobilisation — fleet CAPEX window open now.",
    "BW Opal FPSO commissioning in Darwin — high-volume compressed air and nitrogen demand.",
    "Logan & Gold Coast Faster Rail $5.75B awarded to ActivUs consortium — major earthworks starting H1 2026.",
  ],
  changes: `New this week: 8 projects are new or updated since last report. Change from prior week: Thiess Mount Pleasant expansion confirmed ($900M+ fleet CAPEX signal). Hazel Creek copper-gold drilling campaign announced for March 2026. Two pumped hydro projects declared Critical State Infrastructure in NSW ($7.1B combined).`,
};

export const projects: Project[] = [
  {
    id: "wasp-bulk-earthworks",
    name: "West Angelas Sustaining Project (WASP) — Bulk Earthworks",
    location: "Pilbara, WA",
    value: "$295M",
    owner: "Rio Tinto",
    priority: "hot",
    capexGrade: "A",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: true,
    stage: "Awarded, work commenced Jan 2026",
    overview: "Major bulk earthworks and infrastructure at West Angelas iron ore hub. Includes haul road construction, concrete overpass arch, and access to five new satellite pits at Deposit H. Peak workforce ~220 personnel. NRW awarded $175M for Deposit H; Decmil/Macmahon awarded $120M for Western Hill heavy haulage roads.",
    equipmentSignals: ["Bulk earthworks — compressed air for pneumatic tools", "Concrete works (overpass arch) — air for vibrators", "Haul road construction — drilling and blasting potential", "Remote site — portable air essential, no mains"],
    contractors: [
      { name: "NRW Civil & Mining", status: "confirmed", detail: "$175M bulk earthworks (Deposit H)" },
      { name: "Decmil (Macmahon)", status: "confirmed", detail: "$120M heavy haulage roads (Western Hill)" },
    ],
    opportunityNote: "Both contractors will need portable air for pneumatic tools, concrete vibrators, drilling support. Remote site = portable air essential.",
    sources: [
      { label: "NRW Holdings ASX Release", url: "https://nrw.com.au/nrw-civil-mining-secures-over-250m-in-civil-contract-awards/", date: "Feb 3, 2026" },
      { label: "International Mining", url: "https://im-mining.com/2026/01/19/decmil-to-construct-infrastructure-for-rio-tinto-led-west-angelas-sustaining-project/", date: "Jan 19, 2026" },
    ],
    completion: "2027",
  },
  {
    id: "mnd-rio-tinto-maintenance",
    name: "Monadelphous Rio Tinto Pilbara Maintenance Services",
    location: "Pilbara, WA",
    value: "$300M",
    owner: "Rio Tinto",
    priority: "hot",
    capexGrade: "A",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Awarded Jan 2026",
    overview: "Five-year fixed plant maintenance and scheduled shutdown services across Rio Tinto's Pilbara iron ore operations. Covers generalist mechanical and access services supporting continuous operational reliability.",
    equipmentSignals: ["Shutdown services — high-pressure air for cleaning, testing", "Fixed plant maintenance — instrument air, pneumatic tools", "Crusher/conveyor maintenance — portable air for remote pits"],
    contractors: [{ name: "Monadelphous Group", status: "confirmed", detail: "$300M (5-year term)" }],
    sources: [{ label: "Monadelphous ASX Release", url: "https://www.monadelphous.com.au/investors/asx-announcements/2026/01/monadelphous-awarded-rio-tinto-maintenance-services-contract/", date: "Jan 14, 2026" }],
    timeline: "5-year term",
  },
  {
    id: "golding-meandu",
    name: "Golding Meandu Coal Mine MSA",
    location: "South Burnett, QLD",
    value: "$750M",
    owner: "TEC Coal / Stanwell",
    priority: "hot",
    capexGrade: "A",
    opportunityRoute: "Fleet CAPEX",
    sector: "mining",
    isNew: true,
    stage: "Mobilisation commenced Jan 2026",
    overview: "5.5-year mining services agreement covering whole-of-mine management at Meandu coal mine. Includes operation and maintenance of three fleets of heavy mining equipment, dragline operations, and processing plant management. Six-month mobilisation phase commenced January 2026.",
    equipmentSignals: ["Dragline operations — compressed air for maintenance", "Processing plant — instrument air systems", "Drill & blast — portable air for drilling rigs", "Fleet maintenance — pneumatic tools, 600+ CFM"],
    contractors: [
      { name: "Golding Contractors (NRW Holdings)", status: "confirmed", detail: "$750M MSA" },
      { name: "Action Drill & Blast (NRW)", status: "predicted", confidence: 0.7, detail: "drilling/blasting" },
    ],
    opportunityNote: "Golding mobilising 3 heavy fleets. Dragline + processing plant = ongoing air demand. Mobilisation window open NOW.",
    sources: [
      { label: "Mining Technology", url: "https://www.mining-technology.com/news/nrw-secures-502m-mining-services-contract-from-tec-coal/", date: "Jan 19, 2026" },
      { label: "International Mining", url: "https://im-mining.com/2026/01/19/golding-contractors-wins-mining-services-pact-for-stanwell-meandu-coal-mine/", date: "Jan 19, 2026" },
    ],
    timeline: "Jul 2026 – Dec 2031",
  },
  {
    id: "bw-opal-barossa",
    name: "BW Opal FPSO / Barossa LNG Commissioning",
    location: "Darwin, NT",
    value: "$4.7B",
    owner: "Santos / BW Offshore",
    priority: "hot",
    capexGrade: "B",
    opportunityRoute: "Direct CAPEX",
    sector: "oil_gas",
    isNew: false,
    stage: "Commissioning, first LNG cargo Jan 2026",
    overview: "The BW Opal FPSO (358m, one of the largest ever built) is in active commissioning for the Barossa gas field. First LNG cargo loaded January 2026. Ramping to full capacity by mid-2026. Major compressed air requirements for commissioning, nitrogen purging, and pneumatic testing.",
    equipmentSignals: ["FPSO commissioning — high-volume compressed air (600+ CFM)", "Nitrogen generation/purging — boosters, 10-35 bar", "Pipeline commissioning — high-pressure air testing", "Pneumatic tooling for mechanical completion"],
    contractors: [
      { name: "BW Offshore Australia", status: "confirmed", detail: "FPSO operations" },
      { name: "Monadelphous", status: "predicted", confidence: 0.7, detail: "maintenance services" },
      { name: "Worley", status: "predicted", confidence: 0.6, detail: "commissioning support" },
    ],
    sources: [{ label: "Santos Q4 2025 Report", url: "https://www.santos.com/news/2025-fourth-quarter-report/", date: "Jan 22, 2026" }],
    completion: "Mid-2026",
  },
  {
    id: "thiess-mt-pleasant",
    name: "Thiess Mount Pleasant Operation Expansion",
    location: "Hunter Valley, NSW",
    value: "$900M+",
    owner: "MACH Energy",
    priority: "hot",
    capexGrade: "A",
    opportunityRoute: "Fleet CAPEX",
    sector: "mining",
    isNew: true,
    stage: "Awarded, Jan 2026",
    overview: "Thiess secured a 6-year contract to expand operations at Mount Pleasant coal mine. The expansion includes significant fleet mobilisation for drilling & blasting, loading & hauling operations. This is a major Fleet CAPEX signal — Thiess will be expanding their equipment fleet substantially.",
    equipmentSignals: ["Drilling & blasting — high-pressure air for drill rigs", "Loading & hauling — fleet maintenance air", "Expanded fleet — additional portable units needed"],
    contractors: [{ name: "Thiess (CIMIC Group)", status: "confirmed", detail: "6-year mining services" }],
    opportunityNote: "Thiess expanding fleet for D&B + load/haul. Major portable air demand for drill rigs and maintenance.",
    sources: [{ label: "Thiess/ACS Group Release", url: "https://www.grupoacs.com/press-room/news/press-releases/thiess-secures-six-year-contract-to-expand-operations-at-mount-pleasant-operation-australia/", date: "Jan 12, 2026" }],
    timeline: "6 years",
  },
  {
    id: "logan-gc-faster-rail",
    name: "Logan & Gold Coast Faster Rail",
    location: "Brisbane-Gold Coast, QLD",
    value: "$5.75B",
    owner: "QLD/Federal Govt",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Direct CAPEX",
    sector: "infrastructure",
    isNew: false,
    stage: "Awarded",
    overview: "Major rail project. Track duplication, station upgrades, level crossing removals. ActivUs consortium (ACCIONA, CPB, UGL, SMEC, WSP).",
    equipmentSignals: ["Earthmoving, drilling & blasting for cuttings", "Pneumatic tools for rail construction"],
    contractors: [{ name: "ActivUs (ACCIONA, CPB, UGL, SMEC, WSP)", status: "confirmed" }],
    sources: [{ label: "ACCIONA", url: "https://www.acciona.com.au/updates/news/acciona-awarded-the-major-rail-works-package-for-the-logan-and-gold-coast-faster-rail-project", date: "Feb 6, 2026" }],
  },
  {
    id: "woodside-scarborough",
    name: "Woodside Scarborough Energy Project",
    location: "Offshore WA / Karratha",
    value: "$12.5B",
    owner: "Woodside",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Direct CAPEX",
    sector: "oil_gas",
    isNew: false,
    stage: "94% complete, FPU arrived Jan 2026",
    overview: "FPU arrived Jan 2026. 94% complete. First LNG H2 2026. Pluto Train 2 commissioning underway.",
    equipmentSignals: ["FPU commissioning air, nitrogen, instrument air", "Pipeline tie-in high-pressure testing"],
    contractors: [{ name: "Monadelphous, Worley", status: "predicted", confidence: 0.7 }],
    sources: [{ label: "Woodside Energy", url: "https://www.woodside.com/what-we-do/growth-projects/Scarborough-Energy-Project", date: "Jan 2026" }],
  },
  {
    id: "shell-prelude",
    name: "Shell Prelude FLNG Turnaround 2026",
    location: "Offshore WA",
    value: "Undisclosed",
    owner: "Shell",
    priority: "warm",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "oil_gas",
    isNew: false,
    stage: "Turnaround scheduled 2026",
    overview: "Major maintenance blitz and workforce overhaul of Prelude FLNG. Turnaround scheduled 2026.",
    equipmentSignals: ["LNG turnaround — high-pressure air, nitrogen purging", "Shutdown services — portable air for maintenance"],
    contractors: [{ name: "Turnaround contractors TBD", status: "unknown" }],
    sources: [{ label: "Energy News Bulletin", url: "https://www.energynewsbulletin.net/oil-gas/news-analysis/4410752/shell-eyes-leadership-shake-workforce-overhaul-prelude-flng-struggles-persist", date: "Mar 2025" }],
  },
  {
    id: "orchard-hills-defence",
    name: "Orchard Hills Defence Establishment Upgrade",
    location: "Western Sydney, NSW",
    value: "$508M",
    owner: "Dept of Defence",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Direct CAPEX",
    sector: "defence",
    isNew: false,
    stage: "Awarded",
    overview: "GWEO plan upgrade. New explosive ordnance storage, base facility redevelopment. Hansen Yuncken + ADCO awarded.",
    equipmentSignals: ["Construction air, dryers, pneumatic tools", "Specialised storage construction"],
    contractors: [{ name: "Hansen Yuncken, ADCO Constructions", status: "confirmed" }],
    sources: [{ label: "Australian Defence Magazine", url: "https://www.australiandefence.com.au/news/news/orchard-hills-to-receive-508-million-upgrade", date: "Jan 28, 2026" }],
  },
  {
    id: "gold-duke",
    name: "Gold Duke Project — Pre-Mining Works",
    location: "Wiluna, WA",
    value: "$6.75M",
    owner: "Western Gold Resources",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Fleet CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Early works, first gold Q1 2026",
    overview: "Mining approved at Gold Duke. SSH Mining awarded pre-mining works. First gold Q1 2026.",
    equipmentSignals: ["Open-pit drill & blast, haul road construction", "Site establishment portable air"],
    contractors: [
      { name: "SSH Mining Australia", status: "confirmed" },
      { name: "Delta Consultancy & Drilling", status: "confirmed" },
    ],
    sources: [{ label: "TipRanks", url: "https://www.tipranks.com/news/company-announcements/western-gold-resources-awards-pre-mining-contracts-for-gold-duke-project", date: "Feb 8, 2026" }],
  },
  {
    id: "bowen-basin-coking",
    name: "Bowen Basin Coking Coal Operations Extension",
    location: "Bowen Basin, QLD",
    value: "$900M",
    owner: "Various",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Fleet CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Contract extension",
    overview: "Major contract extension for coking coal operations. Open-cut mining through 2028.",
    equipmentSignals: ["Drill & blast, fleet maintenance air"],
    contractors: [{ name: "Contract details pending", status: "unknown" }],
    sources: [{ label: "Projectory", url: "https://www.projectory.com.au/region/bowen-basin", date: "Feb 2026" }],
  },
  {
    id: "csa-copper-revamp",
    name: "CSA Copper Mine Revamp",
    location: "Cobar, NSW",
    value: "Undisclosed",
    owner: "Harmony Gold",
    priority: "warm",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "2-year revamp commenced",
    overview: "2-year revamp to de-risk and de-bottleneck the mine. Underground compressed air systems critical.",
    equipmentSignals: ["Underground compressed air, drilling, ventilation"],
    contractors: [{ name: "Revamp contractors pending", status: "unknown" }],
    sources: [{ label: "Mining Weekly", url: "https://www.miningweekly.com/article/harmony-gold-says-newly-acquired-australian-copper-mine-requires-two-year-revamp-2026-02-10", date: "Feb 10, 2026" }],
  },
  {
    id: "callide-c-outage",
    name: "Callide C Power Station Outage",
    location: "Biloela, QLD",
    value: "Undisclosed",
    owner: "CS Energy",
    priority: "warm",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "energy",
    isNew: false,
    stage: "Major outage/maintenance",
    overview: "Major outage/maintenance at Callide C power station. Shutdown services mobilising.",
    equipmentSignals: ["Shutdown air, cleaning, pneumatic tools"],
    contractors: [{ name: "KAEFER, Monadelphous", status: "predicted", confidence: 0.6 }],
    sources: [{ label: "WattClarity", url: "https://wattclarity.com.au/articles/2026/01/15-jan-csenergy-first-statement/", date: "Jan 16, 2026" }],
  },
  {
    id: "gladstone-shutdown",
    name: "Gladstone LNG Shutdown Season",
    location: "Gladstone, QLD",
    value: "Undisclosed",
    owner: "Various LNG operators",
    priority: "warm",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "oil_gas",
    isNew: false,
    stage: "Scheduled H1 2026",
    overview: "Annual shutdown season for Gladstone LNG facilities. Multiple turnarounds scheduled.",
    equipmentSignals: ["LNG turnaround air, nitrogen purging, pneumatic tools"],
    contractors: [{ name: "KAEFER, UGL, Monadelphous", status: "predicted", confidence: 0.6 }],
    sources: [{ label: "S&P Global", url: "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/lng/", date: "Jan 2026" }],
  },
  {
    id: "eva-copper",
    name: "Eva Copper Mine Project",
    location: "Cloncurry, QLD",
    value: "Undisclosed",
    owner: "Harmony Gold",
    priority: "warm",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Environmental authority amendment",
    overview: "Environmental authority amendment to extend mine life and increase production. Early stage.",
    equipmentSignals: ["Drilling, blasting, processing plant air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "QLD DETSI", url: "https://www.detsi.qld.gov.au/", date: "Feb 9, 2026" }],
  },
  {
    id: "dampier-link-bridge",
    name: "Dampier Link Bridge Stage 2",
    location: "Dampier, WA",
    value: "$49M",
    owner: "Pilbara Ports",
    priority: "warm",
    capexGrade: "B",
    opportunityRoute: "Fleet CAPEX",
    sector: "infrastructure",
    isNew: false,
    stage: "Design phase",
    overview: "New wharf structure. NRW/Brady Marine 50:50 JV. Marine piling, concrete works.",
    equipmentSignals: ["Marine piling air, concrete vibrators, portable tooling"],
    contractors: [{ name: "NRW + Brady Marine JV", status: "confirmed" }],
    sources: [{ label: "NRW ASX", url: "https://nrw.com.au/nrw-civil-mining-secures-over-250m-in-civil-contract-awards/", date: "Feb 3, 2026" }],
  },
  {
    id: "nsw-bess",
    name: "NSW Long-Duration Energy Storage (6 BESS Projects)",
    location: "Various, NSW",
    value: "Multi-billion",
    owner: "NSW Govt",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "energy",
    isNew: false,
    stage: "Planning/approved",
    overview: "6 battery projects totalling 1.17 GW / 12 GWh. Neoen, BW ESS, Ark Energy, FRV, Bridge Energy, Iberdrola.",
    equipmentSignals: ["Civil construction air for earthworks, electrical installation"],
    contractors: [{ name: "Various, TBD", status: "unknown" }],
    sources: [{ label: "NSW Government", url: "https://www.nsw.gov.au/", date: "Jan 2026" }],
  },
  {
    id: "western-sydney-pumped-hydro",
    name: "Western Sydney Pumped Hydro",
    location: "Lake Burragorang, NSW",
    value: "$3.5B",
    owner: "ZEN Energy",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "energy",
    isNew: false,
    stage: "Critical State Infrastructure declared",
    overview: "1GW pumped hydro. Critical State Infrastructure. Extensive tunnelling, dam construction, drilling & blasting.",
    equipmentSignals: ["Tunnel boring air, drilling & blasting, dam construction"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "NSW Government", url: "https://www.nsw.gov.au/", date: "Jan 2026" }],
  },
  {
    id: "yarrabin-pumped-hydro",
    name: "Yarrabin (Phoenix) Pumped Hydro",
    location: "Mudgee, NSW",
    value: "$3.6B",
    owner: "ACEN Australia",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "energy",
    isNew: false,
    stage: "Critical State Infrastructure declared",
    overview: "800MW pumped hydro in Central-West Orana REZ. Critical State Infrastructure. Major earthworks.",
    equipmentSignals: ["Tunnelling, drilling & blasting, earthworks air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "NSW Government", url: "https://www.nsw.gov.au/", date: "Jan 2026" }],
  },
  {
    id: "omega-taroom",
    name: "Omega/Elixir Taroom Trough Drilling",
    location: "Taroom Trough, QLD",
    value: "Undisclosed",
    owner: "Omega Oil & Gas",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "oil_gas",
    isNew: false,
    stage: "Rig mobilisation May 2026",
    overview: "Extensive drilling campaign. Rig mobilisation May 2026. Potential new oil province.",
    equipmentSignals: ["Drilling rig compressed air, well testing"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Upstream Online", url: "https://www.upstreamonline.com/exploration/australian-indie-plans-extensive-drilling/2-1-1939123", date: "Jan 2026" }],
  },
  {
    id: "beach-cooper-basin",
    name: "Beach Energy Cooper Basin Western Flank Drilling",
    location: "Cooper Basin, SA",
    value: "Undisclosed",
    owner: "Beach Energy",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "oil_gas",
    isNew: false,
    stage: "Mobilising H2 FY26",
    overview: "Drilling campaign on Western Flank. Mobilising H2 FY26. 100% success rate so far.",
    equipmentSignals: ["Drilling rig air, well completion"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Investing News", url: "https://investingnews.com/", date: "Jan 2026" }],
  },
  {
    id: "conocophillips-otway",
    name: "ConocoPhillips Otway Basin Exploration",
    location: "Offshore VIC",
    value: "Undisclosed",
    owner: "ConocoPhillips",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "oil_gas",
    isNew: false,
    stage: "Ongoing to 2028",
    overview: "Ongoing exploration drilling using Transocean Equinox rig. Continues to 2028.",
    equipmentSignals: ["Offshore drilling support air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "ConocoPhillips", url: "https://conocophillipsaustralia.mysocialpinpoint.com/", date: "Jan 2026" }],
  },
  {
    id: "mulga-tank",
    name: "Mulga Tank Drilling Campaign",
    location: "Eastern Goldfields, WA",
    value: "$180K grant",
    owner: "Western Mines Group",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Commenced Jan 2026",
    overview: "Diamond + RC drilling restarted Jan 2026. EIS grant funded.",
    equipmentSignals: ["Diamond & RC drilling compressed air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Mining.com.au", url: "https://mining.com.au/western-mines-restarts-drilling-for-2026/", date: "Jan 2026" }],
  },
  {
    id: "novo-wyloo",
    name: "Novo Resources Wyloo Project",
    location: "Southern Pilbara, WA",
    value: "Undisclosed",
    owner: "Novo Resources",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "RC drilling planned June Q 2026",
    overview: "Maiden RC drilling campaign planned June Q 2026.",
    equipmentSignals: ["RC drilling compressed air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Proactive Investors", url: "https://ca.proactiveinvestors.com/", date: "Jan 2026" }],
  },
  {
    id: "hazel-creek",
    name: "Hazel Creek Copper-Gold Drilling",
    location: "QLD",
    value: "Undisclosed",
    owner: "Breakthrough Minerals",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: true,
    stage: "Diamond Mar 2026, RC Apr 2026",
    overview: "Diamond drilling March 2026, RC drilling April 2026. Major campaign announced Feb 10.",
    equipmentSignals: ["Diamond & RC drilling compressed air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Kapitales", url: "https://www.kapitales.com.au/", date: "Feb 10, 2026" }],
  },
  {
    id: "kincora-nevertire",
    name: "Kincora/AngloGold Nevertire Drilling",
    location: "Macquarie Arc, NSW",
    value: "Undisclosed",
    owner: "Kincora Copper",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Recommenced Feb 2026",
    overview: "Diamond + mud-rotary drilling recommenced Feb 2026. JV with AngloGold Ashanti.",
    equipmentSignals: ["Diamond drilling compressed air"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Junior Mining Network", url: "https://www.juniorminingnetwork.com/", date: "Feb 2026" }],
  },
  {
    id: "rhodes-ridge",
    name: "Rhodes Ridge Iron Ore Feasibility",
    location: "Pilbara, WA",
    value: "$294M study",
    owner: "Rio Tinto / Mitsui",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "Direct CAPEX",
    sector: "mining",
    isNew: false,
    stage: "Feasibility study",
    overview: "$294M feasibility study for 40-50 Mtpa mine. First ore 2030. Long-term pipeline opportunity.",
    equipmentSignals: ["Feasibility drilling, future mine development"],
    contractors: [{ name: "TBD", status: "unknown" }],
    sources: [{ label: "Rio Tinto", url: "https://www.riotinto.com/", date: "Jan 2026" }],
  },
  {
    id: "toodyay-road",
    name: "Toodyay Road Reconstruction",
    location: "WA",
    value: "$46M",
    owner: "Main Roads WA",
    priority: "cold",
    capexGrade: "Unknown",
    opportunityRoute: "OPEX/Monitor",
    sector: "infrastructure",
    isNew: false,
    stage: "Awarded",
    overview: "Road reconstruction and realignment. NRW awarded. Intersection upgrades, shoulder widening.",
    equipmentSignals: ["Road construction pneumatic tools"],
    contractors: [{ name: "NRW Civil & Mining", status: "confirmed" }],
    sources: [{ label: "NRW ASX", url: "https://nrw.com.au/", date: "Feb 3, 2026" }],
  },
];

export const contacts: Contact[] = [
  { name: "Yogesh Prajapati", title: "GM Procurement & Logistics", company: "NRW Holdings", project: "WASP Deposit H", priority: "hot", roleBucket: "Procurement", email: "yogesh.prajapati@nrw.com.au", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Yogesh+Prajapati+NRW" },
  { name: "Jules Pemberton", title: "CEO & Managing Director", company: "NRW Holdings", project: "WASP / Meandu", priority: "hot", roleBucket: "Operations", email: "info@nrw.com.au", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Jules+Pemberton+NRW" },
  { name: "Kim Hyman", title: "CFO", company: "NRW Holdings", project: "WASP / Meandu", priority: "hot", roleBucket: "Finance", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Kim+Hyman+NRW" },
  { name: "Michael Finnegan", title: "Managing Director & CEO", company: "Macmahon (Decmil)", project: "WASP Western Hill", priority: "hot", roleBucket: "Operations", email: "info@macmahon.com.au", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Michael+Finnegan+Macmahon" },
  { name: "Zoran Bebic", title: "Managing Director", company: "Monadelphous Group", project: "Rio Tinto Maintenance", priority: "hot", roleBucket: "Operations", email: "zoran.bebic@monadelphous.com.au", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Zoran+Bebic+Monadelphous" },
  { name: "Paul Thomas", title: "Contracts & Procurement Mgr", company: "Monadelphous Group", project: "Rio Tinto Maintenance", priority: "hot", roleBucket: "Procurement", email: "paul.thomas@monadelphous.com.au", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Paul+Thomas+Monadelphous" },
  { name: "James Bolton", title: "Site Manager", company: "Monadelphous Group", project: "Rio Tinto Maintenance", priority: "hot", roleBucket: "Operations", email: "james.bolton@monadelphous.com.au" },
  { name: "Alex Longworth", title: "Project Manager", company: "Monadelphous Group", project: "Barossa FPSO", priority: "hot", roleBucket: "Project", email: "alex.longworth@monadelphous.com.au" },
  { name: "Michael Gray", title: "CEO", company: "Thiess", project: "Mt Pleasant Expansion", priority: "hot", roleBucket: "Operations", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Michael+Gray+Thiess" },
  { name: "Sean Munroe", title: "Procurement Director", company: "Thiess", project: "Mt Pleasant Expansion", priority: "hot", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Sean+Munroe+Thiess+Procurement" },
  { name: "Kevin Gallagher", title: "MD & CEO", company: "Santos", project: "Barossa / BW Opal", priority: "hot", roleBucket: "Operations", email: "info@santos.com" },
  { name: "John Howarth", title: "Senior Director Procurement", company: "Worley", project: "Scarborough / Barossa", priority: "warm", roleBucket: "Procurement", email: "john.howarth@worley.com", linkedin: "https://www.linkedin.com/search/results/all/?keywords=John+Howarth+Worley" },
  { name: "Murali Jagadeesan", title: "Principal Expeditor", company: "Worley", project: "Scarborough", priority: "warm", roleBucket: "Procurement", email: "murali.jagadeesan@worley.com" },
  { name: "Prasad Vannemreddy", title: "Engineering Manager", company: "Worley", project: "Scarborough", priority: "warm", roleBucket: "Engineering", email: "prasad.vannemreddy@worley.com" },
  { name: "Treeve Andrew", title: "Engineering Manager", company: "Worley", project: "Scarborough", priority: "warm", roleBucket: "Engineering", email: "treeve.andrew@worley.com" },
  { name: "Ross Greenwood", title: "Supply Chain Coordinator", company: "KBR", project: "General", priority: "warm", roleBucket: "Procurement", email: "ross.greenwood@kbr.com" },
  { name: "Bree Thompson", title: "Procurement & Contracts Lead", company: "KBR", project: "General", priority: "warm", roleBucket: "Procurement", email: "bree.thompson@kbr.com" },
  { name: "Otavio Da Silva Martins", title: "Senior Supply Chain Analyst", company: "KBR", project: "General", priority: "warm", roleBucket: "Procurement", email: "otavio.martins@kbr.com" },
  { name: "Paulina Leibovitch", title: "Senior Procurement Admin", company: "KBR", project: "General", priority: "warm", roleBucket: "Procurement", email: "paulina.leibovitch@kbr.com" },
  { name: "Meg O'Neill", title: "MD & CEO", company: "Woodside Energy", project: "Scarborough", priority: "warm", roleBucket: "Operations", email: "info@woodside.com" },
  { name: "Naveen Sebastian", title: "IT Project Manager", company: "Monadelphous", project: "BW Opal FPSO", priority: "hot", roleBucket: "Project", email: "naveen.sebastian@monadelphous.com.au" },
  { name: "Patrick Minchin", title: "Procurement Manager", company: "Clough", project: "General", priority: "warm", roleBucket: "Procurement", email: "patrick.minchin@clough.com.au" },
  { name: "Hansen Yuncken Procurement", title: "Procurement Team", company: "Hansen Yuncken", project: "Orchard Hills Defence", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/hansen-yuncken/" },
  { name: "ADCO Constructions Procurement", title: "Procurement Team", company: "ADCO Constructions", project: "Orchard Hills Defence", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/adco-constructions/" },
  { name: "ACCIONA Procurement", title: "Procurement Team", company: "ACCIONA Infrastructure", project: "Logan-GC Faster Rail", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/acciona-infrastructure-australia/" },
  { name: "CPB Contractors Procurement", title: "Procurement Team", company: "CPB Contractors", project: "Logan-GC Faster Rail", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/cpb-contractors/" },
  { name: "UGL Procurement", title: "Procurement Team", company: "UGL", project: "Logan-GC Faster Rail", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/ugl-limited/" },
  { name: "SSH Mining Contact", title: "Operations", company: "SSH Mining Australia", project: "Gold Duke", priority: "warm", roleBucket: "Operations", linkedin: "https://www.linkedin.com/company/ssh-mining/" },
  { name: "Brady Marine Contact", title: "Operations", company: "Brady Marine & Civil", project: "Dampier Link Bridge", priority: "warm", roleBucket: "Operations", linkedin: "https://www.linkedin.com/company/brady-marine-&-civil/" },
  { name: "Delta Drilling Contact", title: "Operations", company: "Delta Consultancy & Drilling", project: "Gold Duke", priority: "warm", roleBucket: "Operations", linkedin: "https://www.linkedin.com/search/results/all/?keywords=Delta+Consultancy+Drilling" },
  { name: "CS Energy Procurement", title: "Procurement Team", company: "CS Energy", project: "Callide C Outage", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/cs-energy/" },
  { name: "KAEFER Procurement", title: "Procurement Team", company: "KAEFER", project: "Gladstone Shutdown", priority: "warm", roleBucket: "Procurement", linkedin: "https://www.linkedin.com/company/kaefer/" },
  { name: "Keith Mclean", title: "Operations Manager - Civil", company: "MACA", project: "General WA", priority: "cold", roleBucket: "Operations", phone: "+61000000000" },
  { name: "Vibeena Jeyaraj", title: "People & Culture Manager", company: "DDH1 Drilling", project: "General Drilling", priority: "cold", roleBucket: "Operations", email: "vibeena.jeyaraj@ddh1.com.au" },
  { name: "Omega Oil & Gas Contact", title: "Operations", company: "Omega Oil & Gas", project: "Taroom Trough", priority: "cold", roleBucket: "Operations", linkedin: "https://www.linkedin.com/company/omega-oil-and-gas/" },
];

export const drillingCampaigns: DrillingCampaign[] = [
  { campaign: "Mulga Tank", operator: "Western Mines Group", location: "E. Goldfields, WA", drillType: "Diamond + RC", timing: "Commenced Jan 2026", airRequirement: "600-1200 CFM", source: { label: "Mining.com.au", url: "https://mining.com.au/western-mines-restarts-drilling-for-2026/" } },
  { campaign: "Taroom Trough", operator: "Omega Oil & Gas", location: "QLD", drillType: "Oil & Gas wells", timing: "May 2026", airRequirement: "High-pressure", source: { label: "Upstream", url: "https://www.upstreamonline.com/exploration/australian-indie-plans-extensive-drilling/2-1-1939123" } },
  { campaign: "Wyloo Project", operator: "Novo Resources", location: "S. Pilbara, WA", drillType: "RC", timing: "June Q 2026", airRequirement: "600-1200 CFM", source: { label: "Proactive", url: "https://ca.proactiveinvestors.com/" } },
  { campaign: "Hazel Creek Cu-Au", operator: "Breakthrough Minerals", location: "QLD", drillType: "Diamond (Mar) + RC (Apr)", timing: "Mar-Apr 2026", airRequirement: "200-1200 CFM", source: { label: "Kapitales", url: "https://www.kapitales.com.au/" } },
  { campaign: "Cooper Basin W. Flank", operator: "Beach Energy", location: "Cooper Basin, SA", drillType: "Oil & Gas wells", timing: "H2 FY26", airRequirement: "High-pressure", source: { label: "Investing News", url: "https://investingnews.com/" } },
  { campaign: "Otway Basin", operator: "ConocoPhillips", location: "Offshore VIC", drillType: "Exploration wells", timing: "Ongoing to 2028", airRequirement: "Offshore rig air", source: { label: "ConocoPhillips", url: "https://conocophillipsaustralia.mysocialpinpoint.com/" } },
  { campaign: "Nevertire", operator: "Kincora / AngloGold", location: "Macquarie Arc, NSW", drillType: "Diamond + mud-rotary", timing: "Recommenced Feb 2026", airRequirement: "200-400 CFM", source: { label: "JMN", url: "https://www.juniorminingnetwork.com/" } },
  { campaign: "Gold Duke", operator: "Western Gold / Delta", location: "Wiluna, WA", drillType: "RC + blast hole", timing: "Q1 2026", airRequirement: "600-1200 CFM", source: { label: "TipRanks", url: "https://www.tipranks.com/" } },
];

export const awardedProjects: AwardedProject[] = [
  { project: "WASP Deposit H", value: "$175M", winningContractor: "NRW Civil & Mining", location: "Pilbara, WA", stage: "Work commenced", opportunity: "Direct", source: { label: "NRW ASX", url: "https://nrw.com.au/nrw-civil-mining-secures-over-250m-in-civil-contract-awards/" } },
  { project: "WASP Western Hill", value: "$120M", winningContractor: "Decmil (Macmahon)", location: "Pilbara, WA", stage: "Work commenced", opportunity: "Direct", source: { label: "Int'l Mining", url: "https://im-mining.com/2026/01/19/decmil-to-construct-infrastructure-for-rio-tinto-led-west-angelas-sustaining-project/" } },
  { project: "Rio Tinto Maintenance", value: "$300M", winningContractor: "Monadelphous", location: "Pilbara, WA", stage: "Awarded", opportunity: "Direct", source: { label: "MND ASX", url: "https://www.monadelphous.com.au/" } },
  { project: "Meandu Coal MSA", value: "$750M", winningContractor: "Golding (NRW)", location: "S. Burnett, QLD", stage: "Mobilising", opportunity: "Fleet", source: { label: "Mining Tech", url: "https://www.mining-technology.com/news/nrw-secures-502m-mining-services-contract-from-tec-coal/" } },
  { project: "Mt Pleasant Expansion", value: "$900M+", winningContractor: "Thiess (CIMIC)", location: "Hunter Valley, NSW", stage: "Awarded", opportunity: "Fleet", source: { label: "ACS Group", url: "https://www.grupoacs.com/press-room/news/press-releases/thiess-secures-six-year-contract-to-expand-operations-at-mount-pleasant-operation-australia/" } },
  { project: "Logan-GC Faster Rail", value: "$5.75B", winningContractor: "ActivUs (ACCIONA, CPB, UGL)", location: "QLD", stage: "Awarded", opportunity: "Direct", source: { label: "ACCIONA", url: "https://www.acciona.com.au/" } },
  { project: "Orchard Hills Defence", value: "$508M", winningContractor: "Hansen Yuncken, ADCO", location: "W. Sydney, NSW", stage: "Awarded", opportunity: "Direct", source: { label: "ADM", url: "https://www.australiandefence.com.au/" } },
  { project: "Gold Duke Pre-Mining", value: "$6.75M", winningContractor: "SSH Mining, Delta Drilling", location: "Wiluna, WA", stage: "Early works", opportunity: "Fleet", source: { label: "TipRanks", url: "https://www.tipranks.com/" } },
  { project: "Dampier Link Bridge", value: "$49M", winningContractor: "NRW + Brady Marine JV", location: "Dampier, WA", stage: "Design phase", opportunity: "Fleet", source: { label: "NRW ASX", url: "https://nrw.com.au/" } },
  { project: "Toodyay Road", value: "$46M", winningContractor: "NRW Civil & Mining", location: "WA", stage: "Awarded", opportunity: "Monitor", source: { label: "NRW ASX", url: "https://nrw.com.au/" } },
];

export const researchPasses: ResearchPass[] = [
  { pass: "A", focus: "Contract Awards & Appointments", rawProjects: 12, keySources: "ASX Releases, NRW, Monadelphous, Thiess, PV Magazine" },
  { pass: "B", focus: "Mobilisation & Commencement Signals", rawProjects: 6, keySources: "Mining Technology, WattClarity, Industry QLD" },
  { pass: "C", focus: "Oil & Gas / LNG Projects", rawProjects: 4, keySources: "Santos, Woodside, Energy News Bulletin" },
  { pass: "D", focus: "Mining Expansion & New Mines", rawProjects: 10, keySources: "Mining.com, ABC News, Rio Tinto, Agnico Eagle" },
  { pass: "E", focus: "Infrastructure & Construction Mega-Projects", rawProjects: 4, keySources: "ACCIONA, Australian Defence Magazine, Water Power Magazine" },
  { pass: "F", focus: "Shutdown, Turnaround & Maintenance", rawProjects: 4, keySources: "Energy News Bulletin, WattClarity, S&P Global" },
  { pass: "G", focus: "Drilling & Exploration Campaigns", rawProjects: 8, keySources: "Mining.com.au, Upstream, Proactive Investors, Junior Mining Network" },
  { pass: "H", focus: "Queensland & NSW Specific", rawProjects: 7, keySources: "Industry QLD, Mining Weekly, QLD DETSI, Transport NSW" },
];

export const sourceCategories = [
  { name: "ASX Releases (NRW, Monadelphous, Santos, Woodside)", type: "asx" as const },
  { name: "International Mining (im-mining.com)", type: "industry" as const },
  { name: "Mining Technology (mining-technology.com)", type: "industry" as const },
  { name: "Mining Weekly (miningweekly.com)", type: "industry" as const },
  { name: "Mining.com & Mining.com.au", type: "industry" as const },
  { name: "Upstream Online (upstreamonline.com)", type: "industry" as const },
  { name: "Energy News Bulletin", type: "industry" as const },
  { name: "WattClarity (power market)", type: "industry" as const },
  { name: "Proactive Investors", type: "industry" as const },
  { name: "Junior Mining Network", type: "industry" as const },
  { name: "Investing News", type: "industry" as const },
  { name: "PV Magazine (renewables)", type: "industry" as const },
  { name: "Water Power Magazine", type: "industry" as const },
  { name: "Australian Defence Magazine", type: "news" as const },
  { name: "ABC News Australia", type: "news" as const },
  { name: "TipRanks (company announcements)", type: "news" as const },
  { name: "QLD DETSI (environmental authority)", type: "govt" as const },
  { name: "Transport NSW", type: "govt" as const },
  { name: "NSW Government (energy policy)", type: "govt" as const },
  { name: "ACS Group / Thiess releases", type: "asx" as const },
  { name: "ACCIONA corporate releases", type: "asx" as const },
  { name: "S&P Global (commodities)", type: "industry" as const },
  { name: "Industry QLD", type: "industry" as const },
];
