CREATE TABLE `pipelineRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runType` enum('daily','weekly','manual') NOT NULL,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`durationMs` int,
	`feedsFetched` int DEFAULT 0,
	`feedErrors` int DEFAULT 0,
	`articlesIngested` int DEFAULT 0,
	`articlesSkippedKeyword` int DEFAULT 0,
	`articlesDuplicate` int DEFAULT 0,
	`articlesExtracted` int DEFAULT 0,
	`projectsCreated` int DEFAULT 0,
	`projectsDuplicate` int DEFAULT 0,
	`drillingCampaignsCreated` int DEFAULT 0,
	`awardedProjectsCreated` int DEFAULT 0,
	`austenderContracts` int DEFAULT 0,
	`dmirsProjects` int DEFAULT 0,
	`contactsEnriched` int DEFAULT 0,
	`apolloCreditsUsed` int DEFAULT 0,
	`errors` json,
	`sourceStats` json,
	`triggeredBy` varchar(256),
	CONSTRAINT `pipelineRuns_id` PRIMARY KEY(`id`)
);
