CREATE TABLE `campaignContacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`firstName` varchar(128),
	`lastName` varchar(128),
	`title` varchar(256),
	`company` varchar(256) NOT NULL,
	`reviewedCompanyName` varchar(256),
	`email` varchar(320),
	`phone` varchar(64),
	`mobile` varchar(64),
	`score` int NOT NULL DEFAULT 0,
	`tier` enum('tier1_hot','tier2_warm','tier3_enrich','tier4_low','excluded') NOT NULL DEFAULT 'tier3_enrich',
	`titleRelevance` enum('blasting_specialist','decision_maker','operations','other','unknown') NOT NULL DEFAULT 'unknown',
	`enrichmentStatus` enum('not_needed','pending','enriched','not_found','failed') NOT NULL DEFAULT 'pending',
	`apolloPersonId` varchar(128),
	`enrichedEmail` varchar(320),
	`enrichedTitle` varchar(256),
	`enrichedLinkedin` varchar(512),
	`enrichedAt` timestamp,
	`matchedProjectIds` json,
	`matchedProjectCount` int NOT NULL DEFAULT 0,
	`outreachStatus` enum('not_started','email_drafted','pending_approval','approved','sent','replied','bounced','opted_out') NOT NULL DEFAULT 'not_started',
	`draftSubject` text,
	`draftBody` text,
	`draftKeyPoints` json,
	`draftTone` varchar(64),
	`draftGeneratedAt` timestamp,
	`approvedAt` timestamp,
	`approvedBy` int,
	`sentAt` timestamp,
	`sentEmailId` varchar(128),
	`sourceRow` int,
	`nameCheckStatus` varchar(128),
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaignContacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`collateralId` int,
	`collateralName` varchar(256),
	`senderName` varchar(128) NOT NULL,
	`senderEmail` varchar(320) NOT NULL,
	`senderTitle` varchar(256),
	`targetSegment` varchar(128),
	`status` enum('draft','active','paused','completed') NOT NULL DEFAULT 'draft',
	`totalContacts` int NOT NULL DEFAULT 0,
	`enrichedContacts` int NOT NULL DEFAULT 0,
	`emailsDrafted` int NOT NULL DEFAULT 0,
	`emailsApproved` int NOT NULL DEFAULT 0,
	`emailsSent` int NOT NULL DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaigns_id` PRIMARY KEY(`id`)
);
