CREATE TABLE `campaignStagedContacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`batchId` varchar(64) NOT NULL,
	`uploadFileType` varchar(32) NOT NULL DEFAULT 'unknown',
	`batchStatus` varchar(32) NOT NULL DEFAULT 'pending',
	`firstName` varchar(128),
	`lastName` varchar(128),
	`fullNameRaw` varchar(256),
	`title` varchar(256),
	`titleRaw` varchar(256),
	`company` varchar(256),
	`companyRaw` varchar(256),
	`companyCanonical` varchar(256),
	`domain` varchar(256),
	`email` varchar(320),
	`phone` varchar(64),
	`mobile` varchar(64),
	`linkedin` varchar(512),
	`notes` text,
	`classification` varchar(32) NOT NULL DEFAULT 'review_needed',
	`reviewFlags` json,
	`reviewStatus` varchar(32) NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewComment` text,
	`sourceRow` int,
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaignStagedContacts_id` PRIMARY KEY(`id`)
);
