CREATE TABLE `accountResearchRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountName` varchar(512) NOT NULL,
	`objective` varchar(128) NOT NULL,
	`lensMode` varchar(32) NOT NULL,
	`ptLaneFocus` varchar(128),
	`researchDepth` enum('quick','standard','deep') NOT NULL DEFAULT 'quick',
	`knownProjectId` int,
	`sellerLaneContext` varchar(256),
	`userId` int NOT NULL,
	`status` enum('pending','running','complete','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`stakeholderMap` json,
	`salesBrief` json,
	`recommendedActions` json,
	`inputContext` json,
	`promptTokens` int,
	`completionTokens` int,
	`totalTokens` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accountResearchRuns_id` PRIMARY KEY(`id`)
);
