CREATE TABLE `accountPriors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rank` int,
	`canonicalName` varchar(256) NOT NULL,
	`aliases` json,
	`state` varchar(256),
	`segment` varchar(256),
	`scoreOutOf100` float,
	`priorityLevel` varchar(32),
	`productFit` text,
	`likelyApplication` text,
	`whyTarget` text,
	`firstSalesAction` text,
	`suggestedOpeningAngle` text,
	`confidenceLevel` varchar(16),
	`existingHistory` text,
	`salesNotes` text,
	`pumpSalesLC` decimal(14,2),
	`pumpQtySince2021` int,
	`latestPumpSaleYear` int,
	`crmRecordsGrouped` int,
	`crmRoles` varchar(256),
	`crmTypes` varchar(256),
	`phone` varchar(64),
	`email` varchar(320),
	`lane` varchar(32) NOT NULL DEFAULT 'pump',
	`status` varchar(32) NOT NULL DEFAULT 'not_started',
	`owner` varchar(256),
	`nextActionDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accountPriors_id` PRIMARY KEY(`id`)
);
