CREATE TABLE `fullPotentialAccountAliases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`aliasName` varchar(512) NOT NULL,
	`aliasType` enum('legal_name','trading_name','abbreviation','misspelling','site_name','crm_name','project_owner','contractor_name','other') NOT NULL DEFAULT 'other',
	`source` varchar(128),
	`confidenceLevel` enum('high','medium','low','unknown') NOT NULL DEFAULT 'unknown',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fullPotentialAccountAliases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fullPotentialAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stableKey` varchar(512) NOT NULL,
	`canonicalName` varchar(512) NOT NULL,
	`displayName` varchar(512),
	`parentGroup` varchar(256),
	`rowClass` enum('account','site_context','channel_managed','competitor_watch','cluster_signal') NOT NULL DEFAULT 'account',
	`country` varchar(2) NOT NULL DEFAULT 'AU',
	`state` varchar(64),
	`region` varchar(128),
	`segment` varchar(128),
	`subsegment` varchar(128),
	`applicationPlays` json,
	`routeToMarket` enum('direct_ape','cea','cp_aps','cp_blastone','cp_pneumatic_engineering','cp_more_air','nz_distributor','png_oceania','hybrid_strategic','product_support','manual_review','exclude') NOT NULL DEFAULT 'manual_review',
	`ownerName` varchar(256),
	`channelOwner` varchar(256),
	`fpStatus` enum('active_target','develop','watch','qualify','park','exclude') NOT NULL DEFAULT 'qualify',
	`priorityTier` enum('tier_a','tier_b','tier_c','tier_d','unassigned') NOT NULL DEFAULT 'unassigned',
	`platformPushDecision` enum('push_now','push_context','channel_view','qualify_first','park_do_not_push') NOT NULL DEFAULT 'qualify_first',
	`currentRevenueAud` decimal(15,2),
	`fullPotentialAud` decimal(15,2),
	`target2026Aud` decimal(15,2),
	`remainingPotentialAud` decimal(15,2),
	`evidenceSources` json,
	`confidenceLevel` enum('high','medium','low','unknown') NOT NULL DEFAULT 'unknown',
	`currentSupplier` varchar(256),
	`installedBaseStatus` enum('known','partial','unknown','not_applicable') NOT NULL DEFAULT 'unknown',
	`installedBaseNotes` text,
	`c4cStatus` enum('not_in_c4c','lead','prospect','opportunity','quote','won','lost','unknown') NOT NULL DEFAULT 'unknown',
	`nextAction` varchar(512),
	`nextActionDate` timestamp,
	`activeInMyWeek` boolean NOT NULL DEFAULT false,
	`sourceWorkbookVersion` varchar(32),
	`sourceSheet` varchar(128),
	`sourceRowNumber` int,
	`rawSourceJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fullPotentialAccounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `fullPotentialAccounts_stableKey_unique` UNIQUE(`stableKey`)
);
--> statement-breakpoint
CREATE TABLE `fullPotentialActions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`projectId` int,
	`signalId` int,
	`userId` int,
	`ownerName` varchar(256),
	`actionType` enum('account_review','contact_discovery','customer_call','site_visit','channel_handover','installed_base_validation','c4c_create_update','proposal_followup','manager_review','other') NOT NULL DEFAULT 'account_review',
	`recommendedAction` varchar(512),
	`dueDate` timestamp,
	`status` enum('not_started','in_progress','contacted','meeting_booked','quoted','won','lost','deferred','not_relevant','completed') NOT NULL DEFAULT 'not_started',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `fullPotentialActions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fullPotentialImports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workbookVersion` varchar(32) NOT NULL,
	`sourceFileName` varchar(512),
	`importedBy` int,
	`importedByName` varchar(256),
	`rowCount` int NOT NULL DEFAULT 0,
	`createdCount` int NOT NULL DEFAULT 0,
	`updatedCount` int NOT NULL DEFAULT 0,
	`skippedCount` int NOT NULL DEFAULT 0,
	`errorCount` int NOT NULL DEFAULT 0,
	`importSummary` json,
	`importedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fullPotentialImports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fullPotentialSignals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int,
	`projectId` int,
	`signalType` enum('drilling_campaign','awarded_project','live_tender','shutdown_turnaround','pipeline_commissioning','mine_site_activity','civil_application','rental_fleet_signal','competitor_channel_signal','installed_base_signal','contact_discovery_signal','manual','other') NOT NULL DEFAULT 'other',
	`signalTitle` varchar(512) NOT NULL,
	`signalSummary` text,
	`sourceUrl` varchar(1024),
	`sourceName` varchar(256),
	`signalDate` timestamp,
	`state` varchar(64),
	`applicationPlay` varchar(128),
	`routeToMarket` varchar(128),
	`urgency` enum('hot','warm','cold','unknown') NOT NULL DEFAULT 'unknown',
	`confidenceLevel` enum('high','medium','low','unknown') NOT NULL DEFAULT 'unknown',
	`suggestedAction` varchar(512),
	`status` enum('new','reviewed','promoted','dismissed','archived') NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fullPotentialSignals_id` PRIMARY KEY(`id`)
);
