/**
 * Contact Validation Page
 *
 * Admin/rep workflow for reviewing and validating the 5-slot candidate slates
 * generated by the contact waterfall engine.
 *
 * Actions per contact:
 *   Accept        → promotes named_unverified to send_ready (if email present)
 *   Reject        → marks contact as rejected, removes from primary slot
 *   Wrong company → flags mismatch, removes from primary slot
 *   Wrong role    → demotes to backup lane
 *   Backup only   → keeps in DB but removes from primary/commercial/technical
 *
 * LLM contacts are shown in a separate "Suggested Stakeholders" section and
 * cannot be promoted by rep action alone.
 */

import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";
import { getLoginUrl } from "@/const";
import {
  CheckCircle2, XCircle, AlertTriangle, UserX, ArrowDownCircle,
  RefreshCw, Zap, Shield, ShieldCheck, ShieldAlert,
  ChevronDown, ChevronUp, ExternalLink, Mail, Building2,
  Flame, TrendingUp, BarChart3, Users,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

// ── Types ──

type TrustTier = "send_ready" | "named_unverified" | "llm_inferred";
type ValidationAction = "accept" | "reject" | "wrong_company" | "wrong_role" | "backup_only";

interface SlotSnapshot {
  contactId: number;
  name: string;
  title: string;
  company: string;
  email: string | null;
  linkedin: string | null;
  enrichmentSource: string;
  contactTrustTier: TrustTier;
  confidenceScore: string;
  roleRelevance: string;
  roleLane: string;
}

// ── Trust Tier Badge ──

function TrustBadge({ tier }: { tier: TrustTier }) {
  if (tier === "send_ready") {
    return (
      <Badge className="bg-emerald-100 text-emerald-800 border-emerald-200 gap-1 text-[10px] font-semibold">
        <ShieldCheck className="w-3 h-3" /> Send-Ready
      </Badge>
    );
  }
  if (tier === "named_unverified") {
    return (
      <Badge className="bg-amber-100 text-amber-800 border-amber-200 gap-1 text-[10px] font-semibold">
        <Shield className="w-3 h-3" /> Validate First
      </Badge>
    );
  }
  return (
    <Badge className="bg-slate-100 text-slate-600 border-slate-200 gap-1 text-[10px] font-semibold">
      <ShieldAlert className="w-3 h-3" /> AI Only
    </Badge>
  );
}

function SourceBadge({ source }: { source: string }) {
  const colors: Record<string, string> = {
    apollo: "bg-blue-100 text-blue-700 border-blue-200",
    hunter: "bg-purple-100 text-purple-700 border-purple-200",
    linkedin: "bg-sky-100 text-sky-700 border-sky-200",
    web_search: "bg-teal-100 text-teal-700 border-teal-200",
    projectory: "bg-orange-100 text-orange-700 border-orange-200",
    llm: "bg-slate-100 text-slate-500 border-slate-200",
  };
  const cls = colors[source] || "bg-slate-100 text-slate-500 border-slate-200";
  return (
    <Badge className={`${cls} text-[10px] font-medium`}>
      {source}
    </Badge>
  );
}

function LaneBadge({ lane }: { lane: string }) {
  const colors: Record<string, string> = {
    primary: "bg-navy/10 text-navy border-navy/20",
    commercial: "bg-gold/15 text-amber-800 border-gold/30",
    technical: "bg-teal/10 text-teal-800 border-teal/20",
    backup: "bg-slate-100 text-slate-500 border-slate-200",
  };
  const cls = colors[lane] || "bg-slate-100 text-slate-500 border-slate-200";
  return (
    <Badge className={`${cls} text-[10px] font-medium capitalize`}>
      {lane}
    </Badge>
  );
}

// ── Contact Slot Card ──

interface ContactSlotCardProps {
  slotLabel: string;
  slotKey: string;
  snapshot: SlotSnapshot | null;
  projectId: number;
  onActionComplete: () => void;
}

function ContactSlotCard({ slotLabel, slotKey, snapshot, projectId, onActionComplete }: ContactSlotCardProps) {
  const [showNote, setShowNote] = useState(false);
  const [note, setNote] = useState("");
  const [pendingAction, setPendingAction] = useState<ValidationAction | null>(null);

  const submitAction = trpc.contactValidation.submitAction.useMutation({
    onSuccess: (data) => {
      toast(data.promoted ? "Contact promoted to Send-Ready" : "Action recorded", {
        description: `${snapshot?.name} — ${pendingAction?.replace("_", " ")}`,
      });
      setShowNote(false);
      setNote("");
      setPendingAction(null);
      onActionComplete();
    },
    onError: (err) => {
      toast.error("Action failed", { description: err.message });
    },
  });

  const hunterVerify = trpc.contactValidation.hunterVerifyContact.useMutation({
    onSuccess: (data) => {
      const msg = data.action === "email_found"
        ? `Email found and contact promoted: ${data.emailFound}`
        : data.action === "kept_unverified"
        ? `Email found but low confidence (score: ${data.hunterConfidence})`
        : `Hunter could not find email: ${data.reason}`;
      toast(`Hunter: ${data.action}`, { description: msg });
      onActionComplete();
    },
    onError: (err) => {
      toast.error("Hunter verification failed", { description: err.message });
    },
  });

  const handleAction = (action: ValidationAction) => {
    if (action === "reject" || action === "wrong_company") {
      setPendingAction(action);
      setShowNote(true);
      return;
    }
    submitAction.mutate({
      contactId: snapshot!.contactId,
      projectId,
      action,
    });
  };

  if (!snapshot) {
    return (
      <div className="rounded-lg border border-dashed border-border bg-muted/30 p-4 flex items-center justify-center min-h-[120px]">
        <p className="text-xs text-muted-foreground italic">No contact in {slotLabel} slot</p>
      </div>
    );
  }

  const isLlm = snapshot.contactTrustTier === "llm_inferred";

  return (
    <>
      <div className={`rounded-lg border p-4 space-y-3 ${isLlm ? "border-amber-200 bg-amber-50/40" : "border-border bg-card"}`}>
        {/* Header */}
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-semibold text-sm text-foreground truncate">{snapshot.name}</span>
              <LaneBadge lane={snapshot.roleLane} />
            </div>
            <p className="text-xs text-muted-foreground mt-0.5 truncate">{snapshot.title}</p>
            <div className="flex items-center gap-1 mt-0.5 text-xs text-muted-foreground">
              <Building2 className="w-3 h-3 shrink-0" />
              <span className="truncate">{snapshot.company}</span>
            </div>
          </div>
          <div className="flex flex-col items-end gap-1 shrink-0">
            <TrustBadge tier={snapshot.contactTrustTier} />
            <SourceBadge source={snapshot.enrichmentSource} />
          </div>
        </div>

        {/* Contact info */}
        <div className="flex items-center gap-3 text-xs">
          {snapshot.email ? (
            <span className="flex items-center gap-1 text-emerald-700">
              <Mail className="w-3 h-3" />
              <span className="truncate max-w-[180px]">{snapshot.email}</span>
            </span>
          ) : (
            <span className="flex items-center gap-1 text-muted-foreground italic">
              <Mail className="w-3 h-3" /> No email
            </span>
          )}
          {snapshot.linkedin && (
            <a
              href={snapshot.linkedin}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 text-sky-600 hover:text-sky-800 transition-colors"
            >
              <ExternalLink className="w-3 h-3" /> LinkedIn
            </a>
          )}
        </div>

        {/* LLM warning */}
        {isLlm && (
          <div className="flex items-start gap-2 p-2 rounded bg-amber-100 border border-amber-200 text-xs text-amber-800">
            <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
            <span>AI-inferred contact — verify independently before outreach. Cannot be promoted by rep action.</span>
          </div>
        )}

        {/* Actions */}
        {!isLlm && (
          <div className="flex flex-wrap gap-1.5 pt-1 border-t border-border">
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-[11px] gap-1 text-emerald-700 border-emerald-200 hover:bg-emerald-50"
              onClick={() => handleAction("accept")}
              disabled={submitAction.isPending}
            >
              <CheckCircle2 className="w-3 h-3" /> Accept
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-[11px] gap-1 text-red-600 border-red-200 hover:bg-red-50"
              onClick={() => handleAction("reject")}
              disabled={submitAction.isPending}
            >
              <XCircle className="w-3 h-3" /> Reject
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-[11px] gap-1 text-orange-600 border-orange-200 hover:bg-orange-50"
              onClick={() => handleAction("wrong_company")}
              disabled={submitAction.isPending}
            >
              <UserX className="w-3 h-3" /> Wrong company
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-[11px] gap-1 text-slate-600 border-slate-200 hover:bg-slate-50"
              onClick={() => handleAction("wrong_role")}
              disabled={submitAction.isPending}
            >
              <ArrowDownCircle className="w-3 h-3" /> Wrong role
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-[11px] gap-1 text-slate-600 border-slate-200 hover:bg-slate-50"
              onClick={() => handleAction("backup_only")}
              disabled={submitAction.isPending}
            >
              <ArrowDownCircle className="w-3 h-3" /> Backup only
            </Button>
            {!snapshot.email && (
              <Button
                size="sm"
                variant="outline"
                className="h-7 text-[11px] gap-1 text-purple-700 border-purple-200 hover:bg-purple-50"
                onClick={() => hunterVerify.mutate({ contactId: snapshot.contactId, projectId })}
                disabled={hunterVerify.isPending}
              >
                <Zap className="w-3 h-3" />
                {hunterVerify.isPending ? "Searching…" : "Hunter verify"}
              </Button>
            )}
          </div>
        )}
      </div>

      {/* Note dialog for reject/wrong_company */}
      <Dialog open={showNote} onOpenChange={setShowNote}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>
              {pendingAction === "reject" ? "Reject contact" : "Flag wrong company"}
            </DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {pendingAction === "reject"
              ? `Rejecting ${snapshot.name}. This will remove them from primary slots.`
              : `Flagging ${snapshot.name} as wrong company. They will be removed from this project's slate.`}
          </p>
          <Textarea
            placeholder="Optional note (e.g. left company, wrong project, duplicate)"
            value={note}
            onChange={e => setNote(e.target.value)}
            className="resize-none"
            rows={3}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNote(false)}>Cancel</Button>
            <Button
              variant="destructive"
              onClick={() => {
                submitAction.mutate({
                  contactId: snapshot.contactId,
                  projectId,
                  action: pendingAction!,
                  note: note || undefined,
                });
              }}
              disabled={submitAction.isPending}
            >
              Confirm
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

// ── Project Slate Row ──

interface ProjectSlateRowProps {
  project: {
    projectId: number;
    projectName: string | null;
    priority: string | null;
    sector: string | null;
    owner: string | null;
    location: string | null;
    capexGrade: string | null;
    discoveryStatus: string | null;
    slate: {
      totalSlotsFilled: number;
      sendReadySlots: number;
      namedUnverifiedSlots: number;
      llmSlots: number;
      sourcesUsed: string[] | null;
      isStale: boolean;
      generatedAt: Date | null;
      primarySnapshot: SlotSnapshot | null;
      commercialSnapshot: SlotSnapshot | null;
      technicalSnapshot: SlotSnapshot | null;
    } | null;
    hasSlate: boolean;
    slateIsStale: boolean;
  };
  onRefresh: () => void;
}

function ProjectSlateRow({ project, onRefresh }: ProjectSlateRowProps) {
  const [expanded, setExpanded] = useState(false);
  const slateQuery = trpc.contactValidation.getSlate.useQuery(
    { projectId: project.projectId },
    { enabled: expanded }
  );

  const regenerate = trpc.contactValidation.regenerateSlate.useMutation({
    onSuccess: () => {
      toast("Slate regenerated");
      slateQuery.refetch();
      onRefresh();
    },
    onError: (err) => toast.error("Failed", { description: err.message }),
  });

  const hunterBatch = trpc.contactValidation.hunterVerifyProject.useMutation({
    onSuccess: (data) => {
      toast(`Hunter batch: ${data.promoted} promoted`, {
        description: `${data.emailsFound} emails found, ${data.keptUnverified} kept unverified`,
      });
      slateQuery.refetch();
      onRefresh();
    },
    onError: (err) => toast.error("Hunter batch failed", { description: err.message }),
  });

  const priorityColor = project.priority === "hot"
    ? "text-red-600"
    : project.priority === "warm"
    ? "text-orange-500"
    : "text-slate-500";

  const coverageColor = !project.slate
    ? "text-slate-400"
    : project.slate.sendReadySlots >= 3
    ? "text-emerald-600"
    : project.slate.sendReadySlots >= 1
    ? "text-amber-600"
    : "text-red-500";

  const slateData = slateQuery.data;

  return (
    <div className="border border-border rounded-lg overflow-hidden">
      {/* Summary row */}
      <div
        className="flex items-center gap-3 px-4 py-3 bg-card hover:bg-muted/30 cursor-pointer transition-colors"
        onClick={() => setExpanded(v => !v)}
      >
        <div className="flex-1 min-w-0 grid grid-cols-1 sm:grid-cols-4 gap-2">
          <div className="sm:col-span-2">
            <div className="flex items-center gap-2">
              {project.priority === "hot" ? (
                <Flame className="w-3.5 h-3.5 text-red-500 shrink-0" />
              ) : (
                <TrendingUp className="w-3.5 h-3.5 text-orange-400 shrink-0" />
              )}
              <span className="font-medium text-sm truncate">{project.projectName || `Project ${project.projectId}`}</span>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5 truncate">
              {project.owner || "—"} · {project.location || "—"} · {project.sector || "—"}
            </p>
          </div>
          <div className="flex items-center gap-2 text-xs">
            <span className={`font-semibold uppercase ${priorityColor}`}>{project.priority}</span>
            {project.capexGrade && (
              <Badge className="text-[10px] bg-slate-100 text-slate-600 border-slate-200">
                {project.capexGrade}
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-2 text-xs">
            {project.slate ? (
              <>
                <span className={`font-semibold ${coverageColor}`}>
                  {project.slate.sendReadySlots}/{project.slate.totalSlotsFilled} send-ready
                </span>
                {project.slateIsStale && (
                  <Badge className="text-[10px] bg-amber-100 text-amber-700 border-amber-200">stale</Badge>
                )}
              </>
            ) : (
              <span className="text-muted-foreground italic">No slate</span>
            )}
          </div>
        </div>
        <div className="shrink-0 text-muted-foreground">
          {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </div>

      {/* Expanded slate */}
      {expanded && (
        <div className="border-t border-border p-4 bg-background space-y-4">
          {/* Actions bar */}
          <div className="flex items-center gap-2 flex-wrap">
            <Button
              size="sm"
              variant="outline"
              className="h-8 text-xs gap-1"
              onClick={() => regenerate.mutate({ projectId: project.projectId })}
              disabled={regenerate.isPending}
            >
              <RefreshCw className={`w-3 h-3 ${regenerate.isPending ? "animate-spin" : ""}`} />
              Regenerate slate
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-8 text-xs gap-1 text-purple-700 border-purple-200 hover:bg-purple-50"
              onClick={() => hunterBatch.mutate({ projectId: project.projectId })}
              disabled={hunterBatch.isPending}
            >
              <Zap className="w-3 h-3" />
              {hunterBatch.isPending ? "Running Hunter…" : "Hunter verify all"}
            </Button>
            {slateData && (
              <div className="ml-auto flex items-center gap-3 text-xs text-muted-foreground">
                <span className="flex items-center gap-1">
                  <ShieldCheck className="w-3 h-3 text-emerald-600" />
                  {slateData.sendReadySlots} send-ready
                </span>
                <span className="flex items-center gap-1">
                  <Shield className="w-3 h-3 text-amber-500" />
                  {slateData.namedUnverifiedSlots} validate first
                </span>
                <span className="flex items-center gap-1">
                  <ShieldAlert className="w-3 h-3 text-slate-400" />
                  {slateData.llmSlots} AI only
                </span>
              </div>
            )}
          </div>

          {slateQuery.isLoading && (
            <p className="text-sm text-muted-foreground text-center py-4">Loading slate…</p>
          )}

          {slateData && (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              <ContactSlotCard
                slotLabel="Primary"
                slotKey="primary"
                snapshot={(slateData.primarySnapshot as SlotSnapshot | null)}
                projectId={project.projectId}
                onActionComplete={() => { slateQuery.refetch(); onRefresh(); }}
              />
              <ContactSlotCard
                slotLabel="Commercial"
                slotKey="commercial"
                snapshot={(slateData.commercialSnapshot as SlotSnapshot | null)}
                projectId={project.projectId}
                onActionComplete={() => { slateQuery.refetch(); onRefresh(); }}
              />
              <ContactSlotCard
                slotLabel="Technical"
                slotKey="technical"
                snapshot={(slateData.technicalSnapshot as SlotSnapshot | null)}
                projectId={project.projectId}
                onActionComplete={() => { slateQuery.refetch(); onRefresh(); }}
              />
              <ContactSlotCard
                slotLabel="Backup 1"
                slotKey="backup1"
                snapshot={(slateData.backup1Snapshot as SlotSnapshot | null)}
                projectId={project.projectId}
                onActionComplete={() => { slateQuery.refetch(); onRefresh(); }}
              />
              <ContactSlotCard
                slotLabel="Backup 2"
                slotKey="backup2"
                snapshot={(slateData.backup2Snapshot as SlotSnapshot | null)}
                projectId={project.projectId}
                onActionComplete={() => { slateQuery.refetch(); onRefresh(); }}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Stats Bar ──

function StatsBar() {
  const statsQuery = trpc.contactValidation.getValidationStats.useQuery(undefined, {
    staleTime: 60_000,
  });

  const stats = statsQuery.data;
  if (!stats) return null;

  const tier = stats.tierDistribution;
  const sendReady = tier["send_ready"] || 0;
  const namedUnverified = tier["named_unverified"] || 0;
  const llmInferred = tier["llm_inferred"] || 0;
  const total = sendReady + namedUnverified + llmInferred;

  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
      <Card className="border-emerald-200">
        <CardContent className="p-4">
          <div className="text-2xl font-bold text-emerald-700">{sendReady.toLocaleString()}</div>
          <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
            <ShieldCheck className="w-3 h-3 text-emerald-600" /> Send-Ready contacts
          </div>
        </CardContent>
      </Card>
      <Card className="border-amber-200">
        <CardContent className="p-4">
          <div className="text-2xl font-bold text-amber-700">{namedUnverified.toLocaleString()}</div>
          <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
            <Shield className="w-3 h-3 text-amber-500" /> Validate First
          </div>
        </CardContent>
      </Card>
      <Card className="border-slate-200">
        <CardContent className="p-4">
          <div className="text-2xl font-bold text-slate-600">{llmInferred.toLocaleString()}</div>
          <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
            <ShieldAlert className="w-3 h-3 text-slate-400" /> AI Only (blocked)
          </div>
        </CardContent>
      </Card>
      <Card className="border-purple-200">
        <CardContent className="p-4">
          <div className="text-2xl font-bold text-purple-700">
            {stats.hunterStats.promoted}
          </div>
          <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
            <Zap className="w-3 h-3 text-purple-500" /> Hunter promotions
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// ── Main Page ──

export default function ContactValidation() {
  const { user, loading } = useAuth();
  const [, navigate] = useLocation();
  const [refreshKey, setRefreshKey] = useState(0);

  const slatesQuery = trpc.contactValidation.getTop20HotSlates.useQuery(undefined, {
    staleTime: 30_000,
  });

  const generateAll = trpc.contactValidation.generateTop20Slates.useMutation({
    onSuccess: (data) => {
      toast(`Slates generated: ${data.generated}/${data.total}`, {
        description: data.failed > 0 ? `${data.failed} failed` : "All succeeded",
      });
      slatesQuery.refetch();
      setRefreshKey(k => k + 1);
    },
    onError: (err) => toast.error("Generation failed", { description: err.message }),
  });

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-navy" />
      </div>
    );
  }

  if (!user) {
    window.location.href = getLoginUrl();
    return null;
  }

  if (user.role !== "admin") {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center p-8">
          <Shield className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h2 className="text-lg font-semibold">Admin access required</h2>
          <p className="text-sm text-muted-foreground mt-2">Contact validation is restricted to admins.</p>
          <Button className="mt-4" onClick={() => navigate("/")}>Go home</Button>
        </div>
      </div>
    );
  }

  const projects = slatesQuery.data || [];
  const hotProjects = projects.filter(p => p.priority === "hot");
  const warmProjects = projects.filter(p => p.priority === "warm");

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-10">
        <div className="container py-4 flex items-center justify-between gap-4">
          <div>
            <h1 className="text-xl font-bold text-foreground flex items-center gap-2">
              <Users className="w-5 h-5 text-navy" />
              Contact Validation
            </h1>
            <p className="text-xs text-muted-foreground mt-0.5">
              Review and validate the 5-slot candidate slates for hot and warm projects
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              className="gap-1.5"
              onClick={() => slatesQuery.refetch()}
              disabled={slatesQuery.isFetching}
            >
              <RefreshCw className={`w-3.5 h-3.5 ${slatesQuery.isFetching ? "animate-spin" : ""}`} />
              Refresh
            </Button>
            <Button
              size="sm"
              className="gap-1.5 bg-navy text-white hover:bg-navy/90"
              onClick={() => generateAll.mutate()}
              disabled={generateAll.isPending}
            >
              <BarChart3 className="w-3.5 h-3.5" />
              {generateAll.isPending ? "Generating…" : "Generate all slates"}
            </Button>
          </div>
        </div>
      </header>

      <main className="container py-6 space-y-6">
        {/* Stats */}
        <StatsBar />

        {/* Waterfall reference */}
        <Card className="border-navy/20 bg-navy/5">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <BarChart3 className="w-4 h-4 text-navy mt-0.5 shrink-0" />
              <div className="text-xs text-foreground/80 space-y-1">
                <p className="font-semibold text-navy">Source waterfall (highest → lowest priority)</p>
                <p>
                  <span className="font-medium text-blue-700">1. Apollo</span> (verified email, project-linked) →{" "}
                  <span className="font-medium text-teal-700">2. Web/LinkedIn</span> (named, email may be missing) →{" "}
                  <span className="font-medium text-orange-700">3. Projectory</span> (named, often has email) →{" "}
                  <span className="font-medium text-purple-700">4. Hunter</span> (email finder/verifier for already-named contacts only) →{" "}
                  <span className="font-medium text-slate-500">5. LLM</span> (suggested only — never primary)
                </p>
                <p className="text-muted-foreground">
                  Role lanes: <strong>Primary</strong> (PM, Site Mgr, Construction Mgr) ·{" "}
                  <strong>Commercial</strong> (Procurement, Contracts, Purchasing) ·{" "}
                  <strong>Technical</strong> (Operations, Maintenance, Engineering, Hire/Rental)
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Project slates */}
        <Tabs defaultValue="hot">
          <TabsList className="mb-4">
            <TabsTrigger value="hot" className="gap-1.5">
              <Flame className="w-3.5 h-3.5 text-red-500" />
              Hot projects ({hotProjects.length})
            </TabsTrigger>
            <TabsTrigger value="warm" className="gap-1.5">
              <TrendingUp className="w-3.5 h-3.5 text-orange-400" />
              Warm projects ({warmProjects.length})
            </TabsTrigger>
          </TabsList>

          <TabsContent value="hot" className="space-y-3">
            {slatesQuery.isLoading && (
              <p className="text-sm text-muted-foreground text-center py-8">Loading hot projects…</p>
            )}
            {hotProjects.map(p => (
              <ProjectSlateRow
                key={`${p.projectId}-${refreshKey}`}
                project={p}
                onRefresh={() => { slatesQuery.refetch(); setRefreshKey(k => k + 1); }}
              />
            ))}
            {!slatesQuery.isLoading && hotProjects.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-8">No hot projects found.</p>
            )}
          </TabsContent>

          <TabsContent value="warm" className="space-y-3">
            {slatesQuery.isLoading && (
              <p className="text-sm text-muted-foreground text-center py-8">Loading warm projects…</p>
            )}
            {warmProjects.map(p => (
              <ProjectSlateRow
                key={`${p.projectId}-${refreshKey}`}
                project={p}
                onRefresh={() => { slatesQuery.refetch(); setRefreshKey(k => k + 1); }}
              />
            ))}
            {!slatesQuery.isLoading && warmProjects.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-8">No warm projects found.</p>
            )}
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
}
